version: "3.9"
services:
  php:
    image: php:latest
    volumes:
      - .:/app
    build:
      context: .
    tty: true

  nginx:
    image: nginx:latest
    volumes:
      - .:/app
      - ./ngnix.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '8080:80'
    links:
      - php